# Generated by Django 5.1 on 2024-09-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('core', '0002_customer_rename_user_artisan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artisan',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
