# Generated by Django 5.1 on 2024-09-11 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usertype'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
