# Generated by Django 5.1 on 2024-09-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceType',
            new_name='Services',
        ),
    ]
